### ISSUE TITLE
Update to denominator 4.5

### ISSUE THREAD

**Issue by codefromthecrypt** [discoverydns/denominator-discoverydns#1]
denominator 4.5 is out and includes zone write support.

https://github.com/Netflix/denominator/issues/360

**Comment by MisterK** [comment]
@adriancole Thanks. Will try to integrate ASAP.

**Comment by MisterK** [comment]
Finally got the time to push this. All the Live tests are passing. I'll have to finish writing the mock tests as soon as I can.

**Comment by codefromthecrypt** [comment]
Welcome back! :)
